version: '3.8'

services:
  mysql-container:
    build: ./database  # La carpeta de tu Dockerfile de MySQL
    container_name: mysql-container
    ports:
      - "3306:3306"  # Exponer el puerto 3306 de MySQL al puerto 3306 en tu máquina host
    volumes:
      - mysql-data:/var/lib/mysql  # Volumen persistente para los datos de la base de datos
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialización
    networks:
      - app-network

  backend:
    build: ./backend  # La carpeta de tu backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/apiDocker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admi

  frontend:
    build: ./frontend  # La carpeta de tu frontend
    container_name: frontend
    ports:
      - "5500:80"  # Mapear el puerto 80 del contenedor al puerto 5500 del host
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:  # Definir el volumen persistente
    driver: local

networks:
  app-network:
    driver: bridge

