FROM openjdk:17-jdk-slim

WORKDIR /app

# Copiar el script wait-for-it
COPY wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

# Copiar la aplicación
COPY ApiDocker-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

# Configurar el ENTRYPOINT para esperar la base de datos
ENTRYPOINT ["wait-for-it", "mysql-container:3306", "--timeout=30", "--strict", "--", "java", "-jar", "app.jar"]
